
#logging.level.org.springframework=INFO
#
#################### DataSource Configuration ##########################
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/PoseidonCapitalSolution
#spring.datasource.username=root
#spring.datasource.password=rootroot
#
#################### Hibernate Configuration ##########################
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8085

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Iv23liMxGJmG5y9BSULS
#            client-secret: caba9b571f65a8bec59b2c0c22c261802518cc09
#            scope: read:user, user:email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: GitHub
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: id
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PoseidonCapitalSolution
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085
